[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reconfillion"
version = "1.1.0"
authors = [
    { name = "Jun Kawahara", email = "junkawahara@users.noreply.github.com"}
]
description = "Solving combinatorial reconfiguration problems."
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.9"
keywords = ["graph algorithm", "combinatorial reconfiguration", "graphillion"]

dependencies = [
    "graphillion>=1.7"
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Homepage = "https://github.com/junkawahara/reconfillion"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
packages = ["reconfillion"]
